### ISSUE TITLE
authentication is not working

### ISSUE THREAD

**Issue by programming-with-ia** [jln13x/hubatschify#1]
[redirect to this url](https://github.com/login/oauth/authorize?client_id=a4f625d60218fd86de52&scope=read%3Auser%20user%3Aemail&response_type=code&redirect_uri=https%3A%2F%2Fify.hubatsch.dev%2Fapi%2Fauth%2Fcallback%2Fgithub&state=WH2dId42vZcR3lS02SyvLcPweyY9XgSD_8Mq379piOk)

![image](https://github.com/user-attachments/assets/cb205f5f-2ea7-4a89-bb05-256882010c32)

**Comment by jln13x** [comment]
old project, doesnt matter ❤️

**Comment by programming-with-ia** [comment]
@jln13x 

I’ve been exploring all the code across your repositories (I hope you don’t mind), and I’ve learned a lot from it. Your work has been incredibly educational and inspiring. Thanks for sharing so much with the community! ❤️

**Comment by jln13x** [comment]
> @jln13x
> 
> I’ve been exploring all the code across your repositories (I hope you don’t mind), and I’ve learned a lot from it. Your work has been incredibly educational and inspiring. Thanks for sharing so much with the community! ❤️

appreciated it bro, feel free to reach out anytime
